### ISSUE TITLE
about evaluation metrics

### ISSUE THREAD

**Issue by xiang-ao-data** [miccaiif/TransMEF#10]
Thanks for sharing the code.
I noticed that you selected 12 objective evaluation metrics in your AAAI paper. however, I don't see them in the code. I would be very grateful if you could share the code about evaluation metrics.

**Comment by HardworkingLittlequ** [comment]
Hello! Thanks for your attention! I noticed that Xingchen Zhang has compiled one of the most comprehensive database of evaluation metrics for multi-exposure image fusion, and you can refer to this URL: https://github.com/xingchenzhang/MEFB for details.
