### ISSUE TITLE
关于测试

### ISSUE THREAD

**Issue by huhaojin** [miccaiif/TransMEF#11]
为什么新的测试文件还没有进行传输，这样如何检验代码的有效性

**Comment by HardworkingLittlequ** [comment]
您好！

我们已经在github公开了论文中使用的测试代码(256*256 resize后的)。对于任意尺寸图像对的测试，您可以尝试自己编写滑窗融合代码。我们非常抱歉，由于上海疫情的原因，我们刚刚有机会返校，没有及时对github进行更新。但是所有关于论文内使用的训练和测试代码，我们已经全部公开且保证能够正常运行。如果有时间，我们会帮助复现滑窗融合代码。

**Comment by miccaiif** [comment]
We recommend to use the sliding window strategy to fuse input images of arbitrary non-256 * 256 size, i.e., fusing images of 256 * 256 window size at a time.

The code is available now at [fusing intput images with arbitary size](https://github.com/miccaiif/TransMEF/blob/main/fusion_arbitary_size_TransMEF_gray.py)

**Comment by miccaiif** [comment]
@huhaojin We recommend to use the sliding window strategy to fuse input images of arbitrary non-256 * 256 size, i.e., fusing images of 256 * 256 window size at a time.

The code is available now at [fusing intput images with arbitary size](https://github.com/miccaiif/TransMEF/blob/main/fusion_arbitary_size_TransMEF_gray.py)
