### ISSUE TITLE
关于测试

### ISSUE THREAD

**Issue by linqwn** [miccaiif/TransMEF#12]
你好，可以详细说明测试的流程吗？

**Comment by HardworkingLittlequ** [comment]
您好，测试流程在文章中有详细描述。为了方便训练和测试，我们将所有图像resize到256*256进行融合测试，相关代码已在github上公开。

**Comment by miccaiif** [comment]
@linqwn We recommend to use the sliding window strategy to fuse input images of arbitrary non-256 * 256 size, i.e., fusing images of 256 * 256 window size at a time.

The code is available now at [fusing intput images with arbitary size](https://github.com/miccaiif/TransMEF/blob/main/fusion_arbitary_size_TransMEF_gray.py)
