### ISSUE TITLE
Error loading pretrained model

### ISSUE THREAD

**Issue by ash80** [miccaiif/TransMEF#13]
Hi,

While trying to run the following command:
```bash
python fusion_gray_TransMEF.py --model_path ./best_model.pth --test_path ./MEFB_dataset_example/grayscale --result_path transMEF_results
```
with the provided pretrained model, I get a runtime error with lots of missing keys.
![Screenshot 2022-08-10 161301](https://user-images.githubusercontent.com/38047957/183940915-3efd7429-2d50-4970-bfd9-67b54547a8cb.jpg)

Could you please check if the code corresponds to the provided pretrained model?

**Comment by HardworkingLittlequ** [comment]
Hello! Thanks for your attention. In our previous practice, the model was fine. One possible reason is that the model was corrupted during the download process.  If there is indeed a problem, we keep in touch promptly.

**Comment by ash80** [comment]
I tried both the google drive and baidu versions. Both seem to have this issue.

**Comment by ash80** [comment]
Managed to fix it. I had to wrap the model in nn.DataParallel() before loading it with the state dictionary.

**Comment by HardworkingLittlequ** [comment]
That's wonderful. Good luck in your new research!
