### ISSUE TITLE
Code for rgb2ycbcr

### ISSUE THREAD

**Issue by ash80** [miccaiif/TransMEF#14]
Thanks for making the code public. Could you please also provide the inverse of function YCbCr2RGB that you have used to convert the RGB images into YCbCr?

**Comment by HardworkingLittlequ** [comment]
Hello! You can refer to [fusedY2RGB.m](https://github.com/miccaiif/TransMEF/blob/main/fusedY2RGB.m) in the repo.

**Comment by ash80** [comment]
Hi,
[fusedY2RGB.m](https://github.com/miccaiif/TransMEF/blob/main/fusedY2RGB.m) only uses both the (rgb2ycbcr and YCbCr2rgb) but it doesn't define them.
Anyways I was able to successfully invert the ycbcr2rgb to get rgb2ycbcr function. So it's no longer an issue. Thanks
