### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by keviner1** [miccaiif/TransMEF#15]
你好，我有个疑惑是MEFB数据集不带GT图像，那PSNR和SSIM是怎么计算的？

**Comment by HardworkingLittlequ** [comment]
您好，感谢关注！这个问题您可以仔细阅读MEFB原作者的两篇综述文章，其中有详细解释。

1. https://doi.org/10.1016/j.inffus.2021.02.005
2. [10.1109/TPAMI.2021.3078906](https://doi.org/10.1109/TPAMI.2021.3078906)

祝好！
