### ISSUE TITLE
exception for best model

### ISSUE THREAD

**Issue by AutoHDR** [miccaiif/TransMEF#17]
![exception](https://user-images.githubusercontent.com/83151966/219948337-4c4edccb-9bdb-445a-aecb-a857583e71ef.png)

`python fusion_gray_TransMEF.py --model_path './best_model.pth' --test_path './MEFB_dataset/' --result_path './TransMEF_result' 
`

There seems to be something wrong with the model parameters,  am I setting something wrong?  Would you help to check it?

**Comment by miccaiif** [comment]
Hello! Thanks for your attention! This is probably caused by a model path error, so please check the model path carefully.

**Comment by miccaiif** [comment]
You can refer to the 'Frequently Asked Questions' for more details.
