### ISSUE TITLE
关于最终融合结果

### ISSUE THREAD

**Issue by WangL0429** [miccaiif/TransMEF#18]
您好，在您的网络架构中最后是产生三个融合结果，这三个结果是怎么处理的呢？

**Comment by lph223** [comment]
请问训练的模型能用吗

**Comment by miccaiif** [comment]
> 您好，在您的网络架构中最后是产生三个融合结果，这三个结果是怎么处理的呢？

您好，感谢关注！我没有理解您的意思，我们最后只会产生一个融合结果。

**Comment by miccaiif** [comment]
> 请问训练的模型能用吗

您好！模型是可以直接使用的，请按照文档严格核对格式。
