### ISSUE TITLE
什么时候会开放代码呢？

### ISSUE THREAD

**Issue by bladetin** [miccaiif/TransMEF#2]
您好！我拜读了您的论文后，受益良多，请问什么具体时间开放代码呢？希望早日能看到您的代码，谢谢！

**Comment by HardworkingLittlequ** [comment]
> 您好！我拜读了您的论文后，受益良多，请问什么具体时间开放代码呢？希望早日能看到您的代码，谢谢！

您好！感谢您的关注！由于我们最近实在是工作繁忙，代码还在整理中。我们一定会尽快发布代码，不好意思给您带来不便！

**Comment by shinianzhihou** [comment]
十分期待代码的release！！！！送我们个新年礼物吧！！哈哈哈

**Comment by gaiyi7788** [comment]
+1，非常希望能尽快开源学习

**Comment by miccaiif** [comment]
Code is available now!
