### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'grayscale0./MEFB_dataset\\color'

### ISSUE THREAD

**Issue by GuoWena** [miccaiif/TransMEF#21]
您好作者，为什么我无法加载测试的图像，感谢您的回答

**Comment by miccaiif** [comment]
> 您好作者，为什么我无法加载测试的图像，感谢您的回答

您好，听起来貌似是路径的问题，可以参考以下引导进行问题排除：

Please mind your input path. It is likely that the input images are not loaded due to the wrong path. You could attempt to pass the test path to the class test_gray and use an absolute path instead of a relative one.
