### ISSUE TITLE
Question about TransBlock

### ISSUE THREAD

**Issue by shinianzhihou** [miccaiif/TransMEF#4]
In your paper, you mentioned "Concretely, we concatenate the two feature maps from the CNN-Module and the Transformer-Module in TransBlock and input ....".
But the dim of embeddings z, the number of channels in Transformer-Module and how to deal with different resolutions of input images are not described clearly in your paper, which is very important in pratical applications.
Could you please add these details or just simply release the model.py first?

**Comment by HardworkingLittlequ** [comment]
Thanks for your attention. In the paper, we adopted the strategy of rearranging the features of vit to the original image size and then concatting them with the feature maps of CNN and finally inputting them into the EnhanceBlock. More feasible approaches could be further explored. We will definitely release the code as soon as possible, at the latest before the official version of the paper is submitted after the AAAI meeting.

**Comment by shinianzhihou** [comment]
Thanks a lot
