### ISSUE TITLE
Problems about testing 

### ISSUE THREAD

**Issue by CBY-9527** [miccaiif/TransMEF#5]
Thanks for sharing the code. The training can be implemented normally, but there is a problem during the test. I ran the test code and reported an error. The test image should be cropped into 256*256 blocks and combined into the original image size, but the corresponding code was not found. Will the code for generating the original image size be made public?

**Comment by HardworkingLittlequ** [comment]
Hello! Thanks for your attention! We have just released a convenient implementation of this transformation. Please refer to "resize_all.py" for details.

**Comment by HardworkingLittlequ** [comment]
> Thanks for sharing the code. The training can be implemented normally, but there is a problem during the test. I ran the test code and reported an error. The test image should be cropped into 256*256 blocks and combined into the original image size, but the corresponding code was not found. Will the code for generating the original image size be made public?

Hello! Thanks for your attention! We have not implemented this part of the code yet, but we will release it as soon as possible.

**Comment by miccaiif** [comment]
@CBY-9527 We recommend to use the sliding window strategy to fuse input images of arbitrary non-256 * 256 size, i.e., fusing images of 256 * 256 window size at a time.

The code is available now at [fusing intput images with arbitary size](https://github.com/miccaiif/TransMEF/blob/main/fusion_arbitary_size_TransMEF_gray.py)
