### ISSUE TITLE
测试性能

### ISSUE THREAD

**Issue by CBY-9527** [miccaiif/TransMEF#7]
您好,打扰一下.非常感谢能够分享这个工作的代码. 我目前有个小问题,我看到代码页里面说是用MEFB作者提供的工具包进行测试的. MEFB作者提供了各个对比方法的融合结果. 我用MEFB作者提供的融合结果和工具包跑了一下,发现和您论文中结果有些出入,比如MEFNet的PSNR跑的是56.5940 (而TransMEF论文中MEFNet的PSNR是52.9449), 想问一下出现这种情况的原因是什么呢.

**Comment by HardworkingLittlequ** [comment]
> 的工具包进行测试的. MEFB作者提供了各个对比方法的融合结果. 我用MEFB作者提供的融合结果和工具包跑了一下,发现和您论文

您好，感谢关注！我们仅使用了MEFB的benchmark数据集，没有使用MEFB文章开源的测试指标工具包进行指标计算（当时MEFB指标测试工具包还没有开源）。造成指标不一致的原因可能有：1、为了方便训练和测试，我们将MEFB数据集中的所有图像resize到256*256的png格式进行所有方法的测试，格式转换可能会导致一定的偏差。特别是对于PSNR等对噪声较为敏感的指标；2、测试代码可能也存在不一致的情况，如后来我在自己复现融合指标代码时也发现MEFB中的测试代码和我从其他文献中找到的代码存在不一致的情况（我发现的是Qc和Qy指标）。我们在文章中对于所有方法的指标计算都是保持一致的。

我也思考到TransMEF的一个不灵活的地方在于很容易受到输入图像大小的限制，这是由于Transformer导致的，因此我们需要重新resize MEFB数据集进行重新计算。我们目前想到的解决方案是使用滑窗方法进行任意大小图像的融合（即将开源），这样就可以和MEFB文章开源的指标一起对比了。

**Comment by HardworkingLittlequ** [comment]
> 您好,打扰一下.非常感谢能够分享这个工作的代码. 我目前有个小问题,我看到代码页里面说是用MEFB作者提供的工具包进行测试的. MEFB作者提供了各个对比方法的融合结果. 我用MEFB作者提供的融合结果和工具包跑了一下,发现和您论文中结果有些出入,比如MEFNet的PSNR跑的是56.5940 (而TransMEF论文中MEFNet的PSNR是52.9449), 想问一下出现这种情况的原因是什么呢.

之前在多曝光图像融合领域确实没有统一的benchmark和测试代码，MEFB开源后可以都以它作为统一的测试标准，就不会再出现不一致的问题了。

**Comment by CBY-9527** [comment]
> 我们目前想到的解决方案是使用滑窗方法进行任意大小图像的融合（即将开源）

感谢您的解惑,同时也非常期待滑窗方法代码的开源,相信会促进transformer在多曝光融合方向的统一.
